services:
  app:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.11
    volumes:
      - .:/app
      - ./releases/linux_distribution:/app/linux_distribution
    working_dir: /app
    entrypoint: ""
